apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-site-manager-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airflow-site-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-site-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "airflow-site-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}