{{ if .Values.siteManager.clusterRoleBinding.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-airflow-sm-auth-role-binding
  labels:
    {{- include "airflow-site-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ include "airflow-site-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}