kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}-secret
  namespace: {{ .Release.Namespace }}
stringData:
  airflow-user: "{{ .Values.secret.airflow.user }}"
  airflow-password: "{{ .Values.secret.airflow.password }}"
{{- if .Values.secret.dbaas.user }}
  dbaas-user: "{{ .Values.secret.dbaas.user }}"
{{- end }}
{{- if .Values.secret.dbaas.password }}
  dbaas-password: "{{ .Values.secret.dbaas.password }}"
{{- end }}
{{- if .Values.secret.trino.host }}
  trino-host: "{{ .Values.secret.trino.host }}"
{{- end }}
{{- if .Values.secret.trino.port }}
  trino-port: "{{ .Values.secret.trino.port }}"
{{- end }}
{{- if .Values.secret.trino.user }}
  trino-user: "{{ .Values.secret.trino.user }}"
{{- end }}
{{- if .Values.secret.trino.catalog_config }}
  trino-catalog-config: |-
    {{ .Values.secret.trino.catalog_config | toJson }}
{{- end }}
