kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}-secret
  namespace: {{ .Release.Namespace }}
stringData:
  airflow-user: "{{ .Values.secret.airflow.user }}"
  airflow-password: "{{ .Values.secret.airflow.password }}"

