kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}-secret
  namespace: {{ .Release.Namespace }}
stringData:
  airflow-user: "{{ .Values.secret.airflow.user }}"
  airflow-password: "{{ .Values.secret.airflow.password }}"
{{- if .Values.secret.dbaas.user }}
  dbaas-user: "{{ .Values.secret.dbaas.user }}"
{{- end }}
{{- if .Values.secret.dbaas.password }}
  dbaas-password: "{{ .Values.secret.dbaas.password }}"
{{- end }}
