kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
#---Qubership custom change: Labels for Qubership release---
    {{- include "service_only_labels" . | nindent 4 }}
#---Qubership custom change: Labels for Qubership release---
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
  selector:
    name: {{ .Values.service.name }}
