{{- if .Values.statusProvisioner.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "airflow.fullname" . }}-status-provisioner
subjects:
  - kind: ServiceAccount
    name: {{ template "airflow.fullname" . }}-status-provisioner
roleRef:
  kind: Role
  name: {{ template "airflow.fullname" . }}-status-provisioner
  apiGroup: rbac.authorization.k8s.io
{{- end }}