{{- if and .Values.customPreinstallJob.enabled .Values.customPreinstallJob.serviceAccount.create }}
kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-11"
  name: custom-preinstall-job-service-account
{{- end }}