{{ if .Values.customPreinstallJob.enabled }}

{{- $Global := . }}
{{- range $secretName, $secretContent := .Values.customPreinstallJob.extraSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl $secretName $Global | quote }}
  labels:
    release: {{ $Global.Release.Name }}
    chart: "{{ $Global.Chart.Name }}-{{ $Global.Chart.Version }}"
    heritage: {{ $Global.Release.Service }}
{{- with $Global.Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-11"
{{- if $secretContent.type }}
type: {{ $secretContent.type }}
{{- end }}
{{- if $secretContent.data }}
data:
  {{- with $secretContent.data }}
  {{- tpl . $Global | nindent 2 }}
  {{- end }}
{{- end }}
{{- if $secretContent.stringData }}
stringData:
  {{- with $secretContent.stringData }}
  {{- tpl . $Global | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}

{{ end }}