{{- if and .Values.customPreinstallJob.enabled .Values.customPreinstallJob.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-11"
  name: custom-preinstall-job-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: custom-preinstall-job-role
subjects:
- kind: ServiceAccount
  name: custom-preinstall-job-service-account
{{- end }}