{{- define "certDnsNames" -}}
  {{- $dnsNames := list "localhost" (printf "%s-site-manager" (include "airflow-site-manager.fullname" .)) (printf "%s-site-manager.%s" (include "airflow-site-manager.fullname" .) .Release.Namespace) (printf "%s-site-manager.%s.svc" (include "airflow-site-manager.fullname" .) .Release.Namespace) (printf "%s-api-server" (include "airflow.fullname" .)) (printf "%s-api-server.%s" (include "airflow.fullname" .) .Release.Namespace) (printf "%s-api-server.%s.svc" (include "airflow.fullname" .) .Release.Namespace) -}}
    {{- $dnsNames = concat $dnsNames .Values.certManagerInegration.subjectAlternativeName.additionalDnsNames -}}
  {{- $dnsNames | toYaml -}}
{{- end -}}
{{- define "certIpAddresses" -}}
  {{- $ipAddresses := list "127.0.0.1" -}}
  {{- $ipAddresses = concat $ipAddresses .Values.certManagerInegration.subjectAlternativeName.additionalIpAddresses -}}
  {{- $ipAddresses | toYaml -}}
{{- end -}}


{{- if .Values.certManagerInegration.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: airflow-services-tls-certificate
  labels:
    app.kubernetes.io/processed-by-operator: cert-manager
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
    "helm.sh/hook-weight": "-11"
spec:
  secretName: {{ .Values.certManagerInegration.secretName }}
  duration: {{ default 365 .Values.certManagerInegration.duration | mul 24 }}h
  commonName: airflow-services-certificate-cn
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
{{ ( include "certDnsNames" . | indent 4 ) }}
  ipAddresses:
{{ ( include "certIpAddresses" . | indent 4) }}
  issuerRef:
    group: cert-manager.io
  {{- if .Values.certManagerInegration.clusterIssuerName }}
    name: {{ .Values.certManagerInegration.clusterIssuerName }}
    kind: ClusterIssuer
  {{- else }}
    name: airflow-tls-issuer
    kind: Issuer
  {{- end }}
{{- end }}
