{{ if .Values.siteManager.cr.install }}
apiVersion: {{ .Values.siteManager.apiGroup }}/v3
kind: SiteManager
metadata:
  name: {{ include "airflow-site-manager.fullname" . }}
  labels:
    app: {{ include "airflow-site-manager.fullname" . }}
spec:
  sitemanager:
    module: "stateful"
    {{- with .Values.siteManager.startAfter }}
    after:
      {{- range . }}
      - {{ . }}
      {{- end }}
    {{- else }}
    after: []
    {{- end }}
    before: []
    sequence: ["standby", "active"]
    timeout: {{ .Values.siteManager.timeout | default 180 }}
    allowedStandbyStateList: ["down", "degraded"]
    parameters:
      serviceEndpoint: {{ template "disasterRecovery.protocol" . }}{{ include "airflow-site-manager.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ template "disasterRecovery.port" . }}/sitemanager
      healthzEndpoint: {{ template "disasterRecovery.protocol" . }}{{ include "airflow-site-manager.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ template "disasterRecovery.port" . }}/healthz
  {{ end }}